// Jaymod-AC: client-side anti-cheat (Phase 1 + 2).
//
// On receiving "ac_q <txn> <type> <args>" from the server, we run the
// appropriate detector and reply with "ac_r <txn> <result>".

#include <bgame/impl.h>
#include "cg_anticheat.h"

// Phase 2 detectors are Win32-only.  Guard with the same pattern the rest
// of jaymod uses for OS-specific code paths.
#if defined(_WIN32)
  #ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
  #endif
  #include <windows.h>
  #include <psapi.h>
#endif

namespace AC {

///////////////////////////////////////////////////////////////////////////////

namespace {

// CRC32 over a buffer.  Uses the same polynomial as base64::crc32 (zlib /
// standard CRC32-IEEE) so server-side hashes generated by the same helper
// match byte-for-byte.  We re-implement here because base/base64 isn't in
// the cgame's include set.
unsigned long crc32_ieee( const unsigned char* buf, size_t len ) {
    static unsigned long table[256];
    static bool inited = false;
    if (!inited) {
        for (unsigned long i = 0; i < 256; ++i) {
            unsigned long c = i;
            for (int k = 0; k < 8; ++k) {
                c = (c & 1) ? (0xEDB88320u ^ (c >> 1)) : (c >> 1);
            }
            table[i] = c;
        }
        inited = true;
    }
    unsigned long c = 0xFFFFFFFFu;
    for (size_t i = 0; i < len; ++i) {
        c = table[(c ^ buf[i]) & 0xFFu] ^ (c >> 8);
    }
    return c ^ 0xFFFFFFFFu;
}

// ---- Detectors -------------------------------------------------------------

// Hash a file the engine can find via the virtual filesystem.  Returns
// 8-char lowercase hex.  On any failure returns "err".
void detect_fhash( const char* path, char* out, size_t outsz ) {
    if (!path || !*path) { Q_strncpyz( out, "err", outsz ); return; }

    fileHandle_t f;
    const int len = trap_FS_FOpenFile( path, &f, FS_READ );
    if (len <= 0) {
        if (len == 0) trap_FS_FCloseFile( f );
        Q_strncpyz( out, "err", outsz );
        return;
    }

    // Read in chunks so we can hash arbitrarily large paks without
    // doing a 50MB heap alloc.  CRC32 is streaming-friendly.
    const int kChunk = 64 * 1024;
    unsigned char* buf = new unsigned char[ kChunk ];

    static unsigned long crcTable[256];
    static bool          crcTableReady = false;
    if (!crcTableReady) {
        for (unsigned long i = 0; i < 256; ++i) {
            unsigned long c = i;
            for (int k = 0; k < 8; ++k) {
                c = (c & 1) ? (0xEDB88320u ^ (c >> 1)) : (c >> 1);
            }
            crcTable[i] = c;
        }
        crcTableReady = true;
    }

    unsigned long crc = 0xFFFFFFFFu;
    int remaining = len;
    while (remaining > 0) {
        const int want = (remaining < kChunk) ? remaining : kChunk;
        trap_FS_Read( buf, want, f );
        for (int i = 0; i < want; ++i) {
            crc = crcTable[(crc ^ buf[i]) & 0xFFu] ^ (crc >> 8);
        }
        remaining -= want;
    }
    crc ^= 0xFFFFFFFFu;

    trap_FS_FCloseFile( f );
    delete[] buf;

    Com_sprintf( out, outsz, "%08lx", crc );
}

void detect_cvar( const char* name, char* out, size_t outsz ) {
    if (!name || !*name) { Q_strncpyz( out, "err", outsz ); return; }
    // Strip any embedded spaces so the response stays single-token.
    char buf[MAX_CVAR_VALUE_STRING];
    trap_Cvar_VariableStringBuffer( name, buf, sizeof(buf) );
    for (char* p = buf; *p; ++p) {
        if (*p == ' ' || *p == '\t' || *p == '\n' || *p == '"' || *p == '\\')
            *p = '_';
    }
    Q_strncpyz( out, buf, outsz );
}

// ---- Phase 2: module enumeration --------------------------------------------
//
// Returns "<count>:<crc32hex>" where the hash is over a sorted, lowercase,
// newline-joined list of every loaded module's base name.  Server can compare
// this fingerprint against known-good values per ET build; deviations are
// SEV_SOFT for review (a known-good list has to be built up over time).

#if defined(_WIN32)

// Tiny insertion sort for the small module-name list (a typical ET process
// has ~30-50 modules — overkill to pull in <algorithm>).
void sortStrings( char** arr, int n ) {
    for (int i = 1; i < n; ++i) {
        char* cur = arr[i];
        int j = i - 1;
        while (j >= 0 && Q_stricmp( arr[j], cur ) > 0) {
            arr[j + 1] = arr[j];
            --j;
        }
        arr[j + 1] = cur;
    }
}

void detect_modules( char* out, size_t outsz ) {
    HMODULE handles[512];
    DWORD   bytesNeeded = 0;
    if (!EnumProcessModules( GetCurrentProcess(),
                              handles, sizeof(handles), &bytesNeeded ))
    {
        Q_strncpyz( out, "err:enum", outsz );
        return;
    }

    const int requested = (int)(bytesNeeded / sizeof(HMODULE));
    const int n = (requested < 512) ? requested : 512;

    // Collect lowercase base names into a single concatenated buffer.
    static char names[512 * 64];
    static char* ptrs[512];
    char* p = names;
    int   count = 0;

    for (int i = 0; i < n; ++i) {
        char buf[MAX_PATH];
        if (GetModuleBaseNameA( GetCurrentProcess(), handles[i], buf, sizeof(buf) ) == 0)
            continue;

        // Lowercase the name so case-only differences don't change the hash.
        for (char* c = buf; *c; ++c) {
            if (*c >= 'A' && *c <= 'Z') *c += ('a' - 'A');
        }

        const size_t l = strlen( buf );
        if ((p - names) + l + 2 > sizeof(names)) break;

        ptrs[count++] = p;
        memcpy( p, buf, l + 1 );
        p += l + 1;
    }

    sortStrings( ptrs, count );

    // Now hash the sorted list joined by '\n'.
    static unsigned char joined[ sizeof(names) + 512 ];
    size_t jlen = 0;
    for (int i = 0; i < count; ++i) {
        const size_t l = strlen( ptrs[i] );
        if (jlen + l + 1 > sizeof(joined)) break;
        memcpy( joined + jlen, ptrs[i], l );
        jlen += l;
        joined[jlen++] = '\n';
    }

    const unsigned long crc = crc32_ieee( joined, jlen );
    Com_sprintf( out, outsz, "%d:%08lx", count, crc );
}

// ---- Phase 2: memory pattern scanning ---------------------------------------
//
// Built-in signature table — names are stable IDs the server queries by
// (`ac_q <txn> mempat <id>`).  Patterns are byte sequences with a same-length
// mask: mask byte 0xFF = compare, 0x00 = wildcard.
//
// Phase 2 ships a couple of harmless placeholder signatures so the scanner
// path is exercised end-to-end without false-positiving real clients.  Real
// cheat signatures get added here as a build-time policy update.

struct Signature {
    const char*          id;
    const unsigned char* bytes;
    const unsigned char* mask;
    size_t               len;
};

// Placeholder signatures.  These byte sequences are exceedingly unlikely
// to appear in legitimate process memory.  Replace / extend with real
// signatures as research lands.  (Patterns intentionally avoid common
// instruction prefixes to keep false-positive rate at zero.)
static const unsigned char SIG1_BYTES[] = {
    0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE,
    0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE
};
static const unsigned char SIG1_MASK[] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};

static const unsigned char SIG2_BYTES[] = {
    0xFE, 0xED, 0xFA, 0xCE, 0xFE, 0xED, 0xFA, 0xCE,
    0xFE, 0xED, 0xFA, 0xCE, 0xFE, 0xED, 0xFA, 0xCE
};
static const unsigned char SIG2_MASK[] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};

const Signature kSignatures[] = {
    { "sig_test1", SIG1_BYTES, SIG1_MASK, sizeof(SIG1_BYTES) },
    { "sig_test2", SIG2_BYTES, SIG2_MASK, sizeof(SIG2_BYTES) },
};
const int kSignaturesCount = sizeof(kSignatures) / sizeof(kSignatures[0]);

const Signature* findSignature( const char* id ) {
    if (!id || !*id) return NULL;
    for (int i = 0; i < kSignaturesCount; ++i) {
        if (!Q_stricmp( kSignatures[i].id, id ))
            return &kSignatures[i];
    }
    return NULL;
}

// Search a byte buffer for the masked pattern.  Returns true on match.
bool patternMatch( const unsigned char* buf, size_t buflen, const Signature& sig ) {
    if (sig.len == 0 || buflen < sig.len) return false;
    const size_t scanEnd = buflen - sig.len;
    for (size_t i = 0; i <= scanEnd; ++i) {
        bool hit = true;
        for (size_t k = 0; k < sig.len; ++k) {
            if (sig.mask[k] == 0) continue;
            if ((buf[i + k] & sig.mask[k]) != (sig.bytes[k] & sig.mask[k])) {
                hit = false;
                break;
            }
        }
        if (hit) return true;
    }
    return false;
}

void detect_mempat( const char* sigId, char* out, size_t outsz ) {
    const Signature* sig = findSignature( sigId );
    if (!sig) { Q_strncpyz( out, "err:sig", outsz ); return; }

    // Resolve our own module's range so we can skip it during scanning —
    // if a placeholder signature ever did end up matching bytes inside
    // cgame.dll itself, we'd false-positive every legit client.
    HMODULE ownModule = GetModuleHandleA( "cgame_mp_x86.dll" );
    PBYTE   ownStart  = (PBYTE)ownModule;
    PBYTE   ownEnd    = NULL;
    if (ownModule) {
        MODULEINFO mi;
        if (GetModuleInformation( GetCurrentProcess(), ownModule, &mi, sizeof(mi) )) {
            ownEnd = ownStart + mi.SizeOfImage;
        }
    }

    // Walk all committed, readable, non-guard regions.
    PBYTE                     addr = NULL;
    MEMORY_BASIC_INFORMATION  mbi;
    while (VirtualQuery( addr, &mbi, sizeof(mbi) ) == sizeof(mbi)) {
        PBYTE regionBase = (PBYTE)mbi.BaseAddress;
        PBYTE regionEnd  = regionBase + mbi.RegionSize;

        const DWORD readMask = PAGE_READONLY | PAGE_READWRITE
                              | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE
                              | PAGE_EXECUTE_WRITECOPY | PAGE_WRITECOPY;

        bool readable = (mbi.State == MEM_COMMIT)
                     && ((mbi.Protect & readMask) != 0)
                     && ((mbi.Protect & PAGE_GUARD) == 0)
                     && ((mbi.Protect & PAGE_NOACCESS) == 0);

        // Skip our own module range to avoid self-match.
        bool skipOwn = (ownStart && ownEnd
                        && regionBase >= ownStart
                        && regionEnd  <= ownEnd);

        if (readable && !skipOwn && mbi.RegionSize >= sig->len) {
            // VirtualQuery already filtered to committed+readable+non-guard
            // regions, so the pattern walk is safe to run directly.
            if (patternMatch( regionBase, mbi.RegionSize, *sig )) {
                Q_strncpyz( out, "hit", outsz );
                return;
            }
        }

        addr = regionEnd;
        // Safety: if VirtualQuery loops on the same region, bail.
        if (regionEnd <= regionBase) break;
    }

    Q_strncpyz( out, "miss", outsz );
}

// ---- Phase 2.3: full module list (for admin !inspect) ----------------------
//
// Returns space-separated lowercase module base names.  Truncates with a
// trailing "...(N more)" marker if the response would exceed `outsz`.

void detect_modules_list( char* out, size_t outsz ) {
    HMODULE handles[512];
    DWORD   bytesNeeded = 0;
    if (!EnumProcessModules( GetCurrentProcess(),
                              handles, sizeof(handles), &bytesNeeded ))
    {
        Q_strncpyz( out, "err:enum", outsz );
        return;
    }

    const int n = (int)(bytesNeeded / sizeof(HMODULE));
    out[0] = '\0';
    size_t used = 0;
    int    skipped = 0;

    for (int i = 0; i < n; ++i) {
        char buf[MAX_PATH];
        if (GetModuleBaseNameA( GetCurrentProcess(), handles[i], buf, sizeof(buf) ) == 0)
            continue;

        // lowercase
        for (char* c = buf; *c; ++c) {
            if (*c >= 'A' && *c <= 'Z') *c += ('a' - 'A');
        }

        const size_t want = strlen( buf ) + 1;  // +1 for separator
        // Leave 24 chars for the "...(N more)" tail.
        if (used + want + 24 > outsz) { ++skipped; continue; }

        if (used) { out[used++] = ' '; }
        memcpy( out + used, buf, want - 1 );
        used += want - 1;
        out[used] = '\0';
    }

    if (skipped > 0) {
        Com_sprintf( out + used, outsz - used, " ...(%d more)", skipped );
    }
}

// ---- Phase 2.3: loaded pak list --------------------------------------------
//
// Enumerates *.pk3 files in:
//   <fs_basepath>/etmain/, <fs_basepath>/<fs_game>/
//   <fs_homepath>/etmain/, <fs_homepath>/<fs_game>/
//
// Returns space-separated "<dir>/<name>:<size>" tuples.  This catches local
// paks the server doesn't know about (a classic wallhack delivery vector).

void detect_paks_list_dir( const char* dir, char* out, size_t outsz, size_t& used, int& skipped ) {
    if (!dir || !*dir) return;

    char pattern[MAX_PATH];
    Com_sprintf( pattern, sizeof(pattern), "%s\\*.pk3", dir );

    WIN32_FIND_DATAA fd;
    HANDLE h = FindFirstFileA( pattern, &fd );
    if (h == INVALID_HANDLE_VALUE) {
        CG_Printf( "AC.DEBUG: paks: no match for \"%s\"\n", pattern );
        return;
    }
    CG_Printf( "AC.DEBUG: paks: scanning \"%s\"\n", pattern );

    int found = 0;
    do {
        if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) continue;

        // The directory tail (after last \ or /).
        const char* tail = strrchr( dir, '\\' );
        if (!tail) tail = strrchr( dir, '/' );
        tail = tail ? tail + 1 : dir;

        char entry[MAX_PATH + 32];
        Com_sprintf( entry, sizeof(entry), "%s/%s:%u",
            tail, fd.cFileName, (unsigned)fd.nFileSizeLow );

        const size_t want = strlen( entry ) + 1;
        if (used + want + 24 > outsz) { ++skipped; continue; }

        if (used) { out[used++] = ' '; }
        memcpy( out + used, entry, want - 1 );
        used += want - 1;
        out[used] = '\0';
        ++found;
    } while (FindNextFileA( h, &fd ));
    FindClose( h );

    CG_Printf( "AC.DEBUG: paks: \"%s\" -> %d file(s), used=%u skipped=%d\n",
        pattern, found, (unsigned)used, skipped );
}

void detect_paks_list( char* out, size_t outsz ) {
    out[0] = '\0';
    size_t used    = 0;
    int    skipped = 0;

    char basepath[MAX_PATH]; basepath[0] = '\0';
    char homepath[MAX_PATH]; homepath[0] = '\0';
    char fs_game[64];        fs_game[0]  = '\0';

    trap_Cvar_VariableStringBuffer( "fs_basepath", basepath, sizeof(basepath) );
    trap_Cvar_VariableStringBuffer( "fs_homepath", homepath, sizeof(homepath) );
    trap_Cvar_VariableStringBuffer( "fs_game",     fs_game,  sizeof(fs_game)  );

    // DEBUG: dump path config so we can see what we're enumerating.
    CG_Printf( "AC.DEBUG: paks: basepath=\"%s\" homepath=\"%s\" fs_game=\"%s\"\n",
        basepath, homepath, fs_game );

    char dir[MAX_PATH];

    if (basepath[0]) {
        Com_sprintf( dir, sizeof(dir), "%s\\etmain", basepath );
        detect_paks_list_dir( dir, out, outsz, used, skipped );

        if (fs_game[0] && Q_stricmp( fs_game, "etmain" ) != 0) {
            Com_sprintf( dir, sizeof(dir), "%s\\%s", basepath, fs_game );
            detect_paks_list_dir( dir, out, outsz, used, skipped );
        }
    }

    if (homepath[0] && Q_stricmp( homepath, basepath ) != 0) {
        Com_sprintf( dir, sizeof(dir), "%s\\etmain", homepath );
        detect_paks_list_dir( dir, out, outsz, used, skipped );

        if (fs_game[0] && Q_stricmp( fs_game, "etmain" ) != 0) {
            Com_sprintf( dir, sizeof(dir), "%s\\%s", homepath, fs_game );
            detect_paks_list_dir( dir, out, outsz, used, skipped );
        }
    }

    if (!used) {
        Q_strncpyz( out, "(none)", outsz );
        return;
    }

    if (skipped > 0) {
        Com_sprintf( out + used, outsz - used, " ...(%d more)", skipped );
    }
}

#else  // !_WIN32

void detect_modules( char* out, size_t outsz ) {
    Q_strncpyz( out, "unsupported", outsz );
}
void detect_mempat( const char* /*sigId*/, char* out, size_t outsz ) {
    Q_strncpyz( out, "unsupported", outsz );
}
void detect_modules_list( char* out, size_t outsz ) {
    Q_strncpyz( out, "unsupported", outsz );
}
void detect_paks_list( char* out, size_t outsz ) {
    Q_strncpyz( out, "unsupported", outsz );
}

#endif  // _WIN32

} // namespace

///////////////////////////////////////////////////////////////////////////////

void onInit()     {}
void onShutdown() {}

void handleQuery() {
    // ac_q <txn> <type> [args...]
    if (trap_Argc() < 3) return;

    char txn[32];
    char type[32];
    trap_Argv( 1, txn,  sizeof(txn) );
    trap_Argv( 2, type, sizeof(type) );

    char arg1[256];
    arg1[0] = '\0';
    if (trap_Argc() >= 4) trap_Argv( 3, arg1, sizeof(arg1) );

    char result[512];
    result[0] = '\0';

    if (!Q_stricmp( type, "fhash" )) {
        detect_fhash( arg1, result, sizeof(result) );
    }
    else if (!Q_stricmp( type, "cvar" )) {
        detect_cvar( arg1, result, sizeof(result) );
    }
    else if (!Q_stricmp( type, "modules" )) {
        detect_modules( result, sizeof(result) );
    }
    else if (!Q_stricmp( type, "mempat" )) {
        detect_mempat( arg1, result, sizeof(result) );
    }
    else if (!Q_stricmp( type, "paks" )) {
        detect_paks_list( result, sizeof(result) );
    }
    else if (!Q_stricmp( type, "modlist" )) {
        detect_modules_list( result, sizeof(result) );
    }
    else {
        Q_strncpyz( result, "unknown", sizeof(result) );
    }

    // DEBUG: confirm the response handler ran and what we're replying with.
    CG_Printf( "AC.DEBUG: handleQuery txn=%s type=%s arg=%s -> result=%s\n",
        txn, type, arg1, result );

    trap_SendClientCommand( va( "ac_r %s %s", txn, result ) );
}

///////////////////////////////////////////////////////////////////////////////

} // namespace AC
