#ifndef BASE_PROJECT_H
#define BASE_PROJECT_H

// Auto-generated project info header for Jaymod 2.2.0
// Originally generated by project/info.py -h project/info.db

#define JAYMOD_name           "Jaymod"
#define JAYMOD_namef          "jaymod"
#define JAYMOD_namex          "^xJay^4mod"
#define JAYMOD_website        "http://jaymod.clanfu.org"
#define JAYMOD_irc            "irc.freenode.net #jaymod"
#define JAYMOD_author         "Jaybird"
#define JAYMOD_copyright      "Copyright (c) 2005-2011 Jaybird. All Rights Reserved."
#define JAYMOD_versionMajor   "2"
#define JAYMOD_versionMinor   "2"
#define JAYMOD_versionPoint   "0"
#define JAYMOD_versionHex     0x02020000
#define JAYMOD_buildDate      "Unknown"
#define JAYMOD_buildStability "development"
#define JAYMOD_buildTarget    "windows"
#define JAYMOD_repoURL        ""
#define JAYMOD_repoUUID       ""
#define JAYMOD_repoRev        "0"
#define JAYMOD_repoLCRev      "0"
#define JAYMOD_repoLCDate     ""
#define JAYMOD_platformName   "Windows"
#define JAYMOD_platformNamef  "windows"
#define JAYMOD_title          "Jaymod 2.2.0"
#define JAYMOD_titlex         "^xJay^4mod ^f2.2.0"
#define JAYMOD_version        "2.2.0"
#define JAYMOD_versionx       "^f2.2.0"
#define JAYMOD_packageBase    "jaymod-2.2.0"
#define JAYMOD_packageBasev   "jaymod-2.2.0-windows"
#define JAYMOD_pk3            "jaymod-2.2.0.pk3"

#define JAYMOD_WINDOWS
#define JAYMOD_DEVELOPMENT

#endif // BASE_PROJECT_H
